apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-webapp

images:
  - name: webapp
    newTag: main

patchesStrategicMerge:
  - cm-env-vars-patch.yaml
  - deploy-patch.yaml
  - ing-patch.yaml

patches:
  - target:
      kind: HorizontalPodAutoscaler
      name: webapp
    patch: |-
      $patch: delete
