apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-webapp

bases:
  - ../../base
  
images:
  - name: webapp
    newTag: main

patchesStrategicMerge:
  - cm-env-vars-patch.yaml
  - deploy-patch.yaml
  - ing-patch.yaml
